# Generated by Django 5.0.2 on 2024-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qustions',
            new_name='Questions',
        ),
    ]
